#!/bin/sh
os=`uname`
echo "system is "$os
arch=`uname -m`
echo "arch is "$arch
binPath=./bin/
if [ "$os" != "Linux" ]; then
   echo "don't support the sytem and break the install"
   exit 0
fi
if [ $# -ne 2 ]; then
  echo "the format should be tkl-change-password -f conf.json"
  exit 0
elif [ "$1" != "-f"  ]; then
  echo "the format should be tkl-change-password -f conf.json"
  exit 0
fi
confJson=$2
if [ ]
systemctl stop lws-thinkOne
systemctl stop lws-nsbrg
if [ "$arch" = "aarch64" ]; then
  binPath=./bin/arm64/
elif [ "$arch" = "x86_64" ]; then
  binPath=./bin/x64/
else
  echo "don't support the arch and break the install"
  exit 0
fi
if test -f /usr/local/mt/lws/lws-thinkOne/config/thinkOne_conf.json; then
  echo "thinkOne config file exist now!"
else
  echo "there is no thinkOne exist , please install at first"
  exit 0
fi
if test -f /usr/local/mt/lws/lws-nsbrg/config/nsbrg_conf.json; then
  echo "nsbrg config file exist now!"
else
  echo "there is no nsbrg exist , please install at first"
  exit 0
fi
echo "start to modify the password .................."
paraConf() {
    confPara=$(./gwm -txt read -fileType jsonFile -f ${confJson} -dataName ${2})
    echo "rewrite "${2}" with "${confPara}
    ./gwm -txt write -fileType jsonFile -f ${1} -dataType string -dataName ${2} -dataVal ${confPara}
}
tkConfFile="/usr/local/mt/lws/lws-thinkOne/config/thinkOne_conf.json"
nsConfFile="/usr/local/mt/lws/lws-nsbrg/config/nsbrg_conf.json"
tklConfFile="/usr/local/mt/tkl/tkl-main/config.json"
bacNetConfFile="/usr/local/mt/tkl/tkl-bacnet-bridge/config.yml"
#paraConf ${tkConfFile}  netEui
paraConf ${tkConfFile}  ns:broker
paraConf ${tkConfFile}  ns:username
paraConf ${tkConfFile}  ns:password
paraConf ${tkConfFile}  as:broker
paraConf ${tkConfFile}  as:username
paraConf ${tkConfFile}  as:password
paraConf ${tkConfFile}  dms:broker
paraConf ${tkConfFile}  dms:username
paraConf ${tkConfFile}  dms:password

paraConf ${tkConfFile}  postgre:server
paraConf ${tkConfFile}  postgre:user
paraConf ${tkConfFile}  postgre:pswd
paraConf ${tkConfFile}  postgre:dbName
paraConf ${tkConfFile}  postgrebk:server
paraConf ${tkConfFile}  postgrebk:user
paraConf ${tkConfFile}  postgrebk:pswd
paraConf ${tkConfFile}  postgrebk:dbName

redispswd=$(./gwm -txt read -fileType jsonFile -f ${confJson} -dataName redispswd)
./gwm -txt write -fileType jsonFile -f ${tkConfFile} -dataType string -dataName redisDev:pswd -dataVal ${redispswd}
./gwm -txt write -fileType jsonFile -f ${tkConfFile} -dataType string -dataName redisPay:pswd -dataVal ${redispswd}
./gwm -txt write -fileType jsonFile -f ${tkConfFile} -dataType string -dataName redisGw:pswd -dataVal ${redispswd}
./gwm -txt write -fileType jsonFile -f ${tkConfFile} -dataType string -dataName redisDnData:pswd -dataVal ${redispswd}
./gwm -txt write -fileType jsonFile -f ${tkConfFile} -dataType string -dataName redisTemp:pswd -dataVal ${redispswd}



./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName redisGw:pswd -dataVal ${redispswd}

netEui=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName netEui)
nsbroker=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName ns:broker)
nsuname=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName ns:username)
nspswd=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName ns:password)
asuname=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName as:username)
aspswd=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName as:password)
pguname=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName postgrebk:user)
pgpswd=$(./gwm -txt read -fileType jsonFile -f ${tkConfFile} -dataName postgrebk:pswd)
echo "netEui is :"${netEui}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName nsBroker -dataVal ${nsbroker}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName nsUserName -dataVal  ${nsuname}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName nsPassword -dataVal  ${nspswd}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName nmsBroker -dataVal ${nsbroker}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName nmsUserName -dataVal  ${nsuname}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName nmsPassword -dataVal  ${nspswd}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName brgBroker -dataVal ${nsbroker}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName brgUserName -dataVal  ${nsuname}
./gwm -txt write -fileType jsonFile -f ${nsConfFile} -dataType string -dataName brgPassword -dataVal  ${nspswd}

./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinkone:nmsBroker:options:username -dataVal  ${asuname}
./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinkone:nsBroker:options:username -dataVal  ${asuname}
./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinkone:asBroker:options:username -dataVal  ${asuname}
./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinkone:nmsBroker:options:password -dataVal  ${aspswd}
./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinkone:nsBroker:options:password -dataVal  ${aspswd}
./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinkone:asBroker:options:password -dataVal  ${aspswd}

./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinklinkPg:user -dataVal  ${pguname}
./gwm -txt write -fileType jsonFile -f ${tklConfFile} -dataType string -dataName thinklinkPg:password -dataVal  ${pgpswd}


gwm -txt replace -f ${bacNetConfFile} -fileType stringFile -symbolStart username: -symbolEnd password: -dataVal ${asuname}$'\n'
gwm -txt replace -f ${bacNetConfFile} -fileType stringFile -symbolStart password: -symbolEnd transfer_topic: -dataVal ${aspswd}$'\n'

gwm -txt replace -f ${bacNetConfFile} -fileType stringFile -symbolStart postgres:// -symbolEnd : -dataVal ${pguname}
gwm -txt replace -f ${bacNetConfFile} -fileType stringFile -symbolStart postgres://postgres: -symbolEnd @127.0.0.1: -dataVal ${pgpswd}


systemctl enable lws-thinkOne
systemctl daemon-reload
systemctl restart lws-thinkOne

systemctl enable lws-nsbrg
systemctl daemon-reload
systemctl restart lws-nsbrg

systemctl enable tkl-main
systemctl daemon-reload
systemctl restart tkl-main
echo "change complete !!!!"